# Generated by Django 3.2.13 on 2022-05-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('active', models.BooleanField(default=True, help_text='Является активным.', verbose_name='Активный')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Слаг — это часть URL-адреса, которая идентифицирует страницу с помощью удобочитаемых ключевых слов.', max_length=255, unique=True, verbose_name='Слаг')),
                ('kind', models.IntegerField(choices=[('choice', 'Choice'), ('range', 'Range'), ('bool', 'Bool')], verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Особенности',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='GroupsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('active', models.BooleanField(default=True, help_text='Является активным.', verbose_name='Активный')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_features', to='product.producttype', verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Группы Особенностей',
                'verbose_name_plural': 'Группы Особенностей',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('active', models.BooleanField(default=True, help_text='Является активным.', verbose_name='Активный')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.featurekey', verbose_name='Особенность')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Значения',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.AddField(
            model_name='featurekey',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_features', to='feature.groupsfeature', verbose_name='Группа Особенности'),
        ),
    ]
